import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return knex.schema
    .createTable('subject', function (table) {
      table.increments('id', { primaryKey: true });
      table.string('denomination').unique().notNullable();
    })
    .then(() => {
      return knex.schema.raw(`
      INSERT INTO subject (denomination) VALUES
        -- Languages
        ('Language'),
        ('English'),
        ('Business English'),
        ('Technical Writing'),
        ('Academic Writing'),
        ('Spanish'),
        ('French'),
        ('German'),
        ('Chinese'),
        ('Japanese'),
        ('Arabic'),
        ('Russian'),
        ('Italian'),
        ('Korean'),
        ('Portuguese'),
        ('Hindi'),
        ('Turkish'),
        ('Vietnamese'),
        ('Thai'),
        ('Greek'),
        ('Polish'),
        ('Swedish'),
        ('Sign Language'),
        ('Latin'),

        -- Science & Applied Sciences
        ('Science'),
        ('Physics'),
        ('Chemistry'),
        ('Biology'),
        ('Environmental Science'),
        ('Astronomy'),
        ('Earth Science'),
        ('General Science'),
        ('Applied Sciences'),
        ('Genetics'),
        ('Microbiology'),
        ('Neuroscience'),
        ('Quantum Physics'),
        ('Forensic Science'),
        ('Marine Biology'),
        ('Zoology'),
        ('Meteorology'),
        ('Biochemistry'),
        ('Organic Chemistry'),
        ('Nuclear Physics'),
        ('Botany'),
        ('Ecology'),
        ('Bioinformatics'),
        ('Immunology'),
        ('Virology'),
        ('Paleontology'),
        ('Pharmacology'),
        ('Food Science'),
        ('Materials Science'),
        ('Biophysics'),
        ('Molecular Biology'),
        ('Conservation Biology'),

        -- Mathematics
        ('Mathematics'),
        ('Calculus'),
        ('Statistics'),
        ('Algebra'),
        ('Geometry'),
        ('Trigonometry'),
        ('Linear Algebra'),
        ('Discrete Mathematics'),
        ('Number Theory'),
        ('Mathematical Logic'),
        ('Probability'),
        ('Financial Mathematics'),
        ('Cryptography'),
        ('Game Theory'),
        ('Complex Analysis'),
        ('Real Analysis'),
        ('Topology'),
        ('Graph Theory'),
        ('Optimization'),
        ('Actuarial Mathematics'),

        -- Social Sciences
        ('Social Science'),
        ('History'),
        ('Geography'),
        ('Economics'),
        ('Psychology'),
        ('Sociology'),
        ('Political Science'),
        ('Philosophy'),
        ('Cultural Studies'),
        ('World Cultures'),
        ('Anthropology'),
        ('Religious Studies'),
        ('Gender Studies'),
        ('Media Studies'),
        ('Cultural Heritage'),
        ('International Relations'),
        ('Archaeology'),
        ('Public Policy'),
        ('Urban Planning'),
        ('Human Rights'),
        ('Environmental Studies'),

        -- Technology & Computing
        ('Technology & Computing'),
        ('Artificial Intelligence'),
        ('AI Fundamentals'),
        ('Machine Learning'),
        ('Deep Learning'),
        ('Neural Networks'),
        ('Data Science'),
        ('AI Ethics'),
        ('Computer Vision'),
        ('Natural Language Processing'),
        ('Modern Technologies'),
        ('Virtual Reality'),
        ('Augmented Reality'),
        ('Blockchain'),
        ('Internet of Things'),
        ('Cloud Computing'),
        ('Mobile App Development'),
        ('Game Development'),
        ('Computer Science'),
        ('Information Technology'),
        ('Programming'),
        ('Web Development'),
        ('Digital Media'),
        ('Robotics'),
        ('Cybersecurity'),
        ('Database Management'),
        ('DevOps'),
        ('Software Testing'),
        ('Network Security'),
        ('System Administration'),
        ('Big Data'),
        ('Quantum Computing'),
        ('Embedded Systems'),
        ('Operating Systems'),
        ('Edge Computing'),
        ('5G Technology'),
        ('Microservices'),
        ('API Development'),
        ('Low-Code Development'),
        ('NoSQL Databases'),
        ('Serverless Computing'),
        ('IT Service Management'),
        ('Digital Forensics'),
        ('Penetration Testing'),
        ('Mobile Security'),
        ('Cryptocurrency'),
        ('Smart Contracts'),
        ('UI Development'),
        ('Frontend Development'),
        ('Backend Development'),
        ('Full Stack Development'),

        -- Digital & Creative
        ('Digital'),
        ('Content Creation'),
        ('Social Media'),
        ('Digital Marketing'),
        ('Animation'),
        ('3D Modeling'),
        ('UX/UI Design'),
        ('Video Production'),
        ('Arts & Music'),
        ('Visual Arts'),
        ('Music'),
        ('Drama'),
        ('Dance'),
        ('Photography'),
        ('Graphic Design'),
        ('Film Studies'),
        ('Modern Arts'),
        ('Digital Art'),
        ('Street Art'),
        ('Contemporary Art'),
        ('Art History'),
        ('Comic Art'),
        ('Character Design'),
        ('Motion Graphics'),
        ('Sound Design'),
        ('Music Production'),
        ('Music Theory'),
        ('Voice Acting'),
        ('Creative Writing'),
        ('Screenwriting'),
        ('Podcast Production'),
        ('Digital Photography'),
        ('Color Theory'),
        ('Typography'),
        ('Brand Design'),
        ('Game Design'),
        ('Level Design'),
        ('Visual Effects'),
        ('Digital Sculpting'),
        ('Concept Art'),
        ('Storyboarding'),

        -- Business & Professional
        ('Business Studies'),
        ('Business Management'),
        ('Accounting'),
        ('Marketing'),
        ('Finance'),
        ('Entrepreneurship'),
        ('Business Analytics'),
        ('Human Resources'),
        ('Supply Chain Management'),
        ('Operations Management'),
        ('Risk Management'),
        ('Investment Banking'),
        ('Real Estate'),
        ('International Business'),
        ('E-commerce'),
        ('Sales'),
        ('Corporate Law'),
        ('Business Ethics'),
        ('Data Analytics'),
        ('Digital Transformation'),
        ('Change Management'),
        ('Business Intelligence'),
        ('Product Management'),
        ('Agile Management'),
        ('Quality Management'),
        ('Customer Experience'),
        ('Strategic Planning'),
        ('Tax Planning'),
        ('Investment Management'),
        ('Cryptocurrency Trading'),
        ('Startup Management'),

        -- Personal Development
        ('Public Speaking'),
        ('Leadership'),
        ('Project Management'),
        ('Critical Thinking'),
        ('Time Management'),
        ('Communication Skills'),
        ('Research Methods'),
        ('Emotional Intelligence'),
        ('Stress Management'),
        ('Personal Finance'),
        ('Career Development'),
        ('Negotiation Skills'),
        ('Problem Solving'),
        ('Decision Making'),
        ('Mindfulness'),
        ('Personal Branding'),
        ('Work-Life Balance'),
        ('Goal Setting'),
        ('Memory Techniques'),
        ('Speed Reading'),
        ('Personal Productivity'),
        ('Relationship Management'),
        ('Conflict Resolution'),
        ('Cultural Intelligence'),
        ('Digital Wellness'),

        -- Health & Physical Education
        ('Physical Education'),
        ('Sports Science'),
        ('Health Education'),
        ('Fitness'),
        ('Athletics'),
        ('Nutrition'),
        ('Mental Health'),
        ('Yoga'),
        ('Meditation'),
        ('Sports Psychology'),
        ('First Aid'),
        ('Anatomy'),
        ('Physical Therapy'),
        ('Sports Management'),
        ('Sports Coaching'),
        ('Exercise Physiology'),
        ('Injury Prevention'),
        ('Rehabilitation'),
        ('Sports Nutrition'),
        ('Movement Science'),
        ('Pilates'),
        ('CrossFit'),
        ('Martial Arts'),
        ('Dance Fitness'),
        ('Alternative Medicine'),
        ('Holistic Health'),

        -- Engineering & Technical
        ('Engineering'),
        ('Electronics'),
        ('Architecture'),
        ('Design Technology'),
        ('Biotechnology'),
        ('Mechanical Engineering'),
        ('Civil Engineering'),
        ('Electrical Engineering'),
        ('Chemical Engineering'),
        ('Aerospace Engineering'),
        ('Software Engineering'),
        ('Industrial Engineering'),
        ('Environmental Engineering'),

        -- Vocational & Practical
        ('Vocational Subjects'),
        ('Home Economics'),
        ('Culinary Arts'),
        ('Textile Studies'),
        ('Woodworking'),
        ('Automotive'),
        ('Plumbing'),
        ('Electrical Trade'),
        ('Welding'),
        ('HVAC'),
        ('Construction'),
        ('Agriculture'),
        ('Horticulture'),
        ('Fashion Design'),
        ('Interior Design'),
        ('Beauty & Cosmetics'),
        ('Hospitality Management'),
        ('Social Media Marketing'),
        ('Content Marketing'),
        ('Email Marketing'),
        ('SEO'),
        ('SEM'),
        ('Copywriting'),
        ('Event Management'),
        ('Wedding Planning'),
        ('Interior Decoration'),
        ('Landscape Design'),
        ('Makeup Artistry'),
        ('Hair Styling'),
        ('Pet Grooming'),
        ('Floral Design'),
        ('Wine Studies'),
        ('Bartending'),
        ('Barista Training'),

        -- Sustainability & Environment
        ('Sustainable Development'),
        ('Climate Science'),
        ('Renewable Energy'),
        ('Green Technology'),
        ('Environmental Conservation'),
        ('Waste Management'),
        ('Sustainable Agriculture'),
        ('Urban Sustainability'),

        -- Education & Teaching
        ('Special Education'),
        ('Learning Support'),
        ('Gifted Education'),
        ('Early Intervention'),
        ('Behavior Support'),
        ('Special Needs'),
        ('Elementary Education'),
        ('Early Childhood'),
        ('Primary Education'),
        ('Elementary Math'),
        ('Elementary Science'),
        ('Elementary Literacy'),
        ('Educational Technology'),
        ('Curriculum Development'),
        ('Teaching Methods'),
        ('Distance Learning'),
        ('Educational Psychology'),
        ('Online Teaching'),
        ('Blended Learning'),
        ('Educational Leadership'),
        ('Student Assessment'),
        ('Classroom Management'),
        ('STEM Education'),
        ('Montessori Education'),
        ('Waldorf Education'),
        ('Language Teaching'),
        ('Music Education'),
        ('Art Education'),
        ('Physical Education Teaching'),
        ('Special Needs Education');
      `);
    });
}

export async function down(knex: Knex): Promise<void> {
  return knex.schema.dropTable('subject');
}
