export enum ErrorType {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SIGN_UP_FIRST = "SIGN_UP_FIRST",
  INVALID_STATE = "INVALID_STATE",
  OIDC_NOT_FOUND = 'OIDC_NOT_FOUND',
  OIDC_INITIALIZE_FAILED = 'OIDC_INITIALIZE_FAILED',
  OIDC_INVALID_PROVIDER = 'OIDC_INVALID_PROVIDER',
}
